In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/General_Offenses_(Open_Data)_7435779472384193066.csv')
print(dfCrime.shape)
dfCrime.head()

(337854, 28)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_9349/3360715205.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/General_Offenses_(Open_Data)_7435779472384193066.csv')

,OBJECTID,PrimaryKey,OccurrenceDatetime,OccurrenceYear,OccurrenceMonth,OccurrenceHour,OccurrenceWeek,OccurrenceDatePart,OccurrenceWeekday,ObfuscatedAddress,...,RucrComp,CharacterArea,ReportDistrict,ReportBeat,PostalCode,CensusTractID,ParkName,NeighborhoodName,x,y
0,109892033,TE2013102138,8/16/2013 12:45:00 PM,2013.0,8.0,12.0,33.0,16.0,Friday,9XX E BROADWAY RD,...,C,Alameda,S,20,85282.0,4.013320e+09,NaN,NaN,697343.0,875784.0
1,109892034,TE2013104042,8/19/2013 3:44:00 PM,2013.0,8.0,15.0,34.0,19.0,Monday,HARDY DR / W UNIVERSITY DR,...,C,Rio Salado/DT/ASU/NW Neighborhoods,N,13,85281.0,4.013319e+09,NaN,NaN,689158.0,881039.0
2,109892035,TE2013104050,8/16/2013 6:00:00 PM,2013.0,8.0,18.0,33.0,16.0,Friday,6XXX S RURAL RD,...,C,Kiwanis/The Lakes,S,21,85283.0,4.013320e+09,NaN,NaN,696260.0,861054.0
3,109892036,TE2013104316,8/20/2013 7:59:00 AM,2013.0,8.0,7.0,34.0,20.0,Tuesday,1XXX N SCOTTSDALE RD,...,C,Papago/North Tempe,N,11,85288.0,4.013318e+09,NaN,Indian Bend,697930.0,890057.0
4,109892037,TE2013105261,8/22/2013 9:37:00 AM,2013.0,8.0,9.0,34.0,22.0,Thursday,2XXX E APACHE BLVD,...,C,Apache,N,15,85281.0,4.013319e+09,NaN,NaN,705067.0,878463.0

In [3]:
dfCrime = dfCrime[dfCrime['OccurrenceYear'].isin([2019, 2018, 2017])]
print(dfCrime.shape)
dfCrime.head()

(84054, 28)

,OBJECTID,PrimaryKey,OccurrenceDatetime,OccurrenceYear,OccurrenceMonth,OccurrenceHour,OccurrenceWeek,OccurrenceDatePart,OccurrenceWeekday,ObfuscatedAddress,...,RucrComp,CharacterArea,ReportDistrict,ReportBeat,PostalCode,CensusTractID,ParkName,NeighborhoodName,x,y
1332,109893365,TE201728621,3/10/2017 12:31:00 PM,2017.0,3.0,12.0,10.0,10.0,Friday,5XXX S ARIZONA MILLS CIR,...,C,Mills/Emerald,S,21,85282.0,4.013320e+09,NaN,NaN,685382.0,866933.0
8782,109900815,TE2017135496,11/13/2017 5:11:00 PM,2017.0,11.0,17.0,46.0,13.0,Monday,3XXX S MILL AVE,...,C,Alameda,S,19,85282.0,4.013320e+09,NaN,NaN,693020.0,869227.0
15134,109907167,TE201729855,3/13/2017 6:42:00 AM,2017.0,3.0,6.0,11.0,13.0,Monday,1XXX E TEMPE DR,...,C,Papago/North Tempe,N,11,85288.0,4.013318e+09,NaN,East Rio,698967.0,888432.0
29656,109921689,TE201818686,2/12/2018 10:00:00 PM,2018.0,2.0,22.0,7.0,12.0,Monday,2XXX E FREMONT DR,...,C,Kiwanis/The Lakes,S,22,85282.0,4.013319e+09,NaN,Cole Park,705054.0,867024.0
46405,109938438,TE201729363,3/12/2017 12:08:00 AM,2017.0,3.0,0.0,11.0,12.0,Sunday,1XXX N SCOTTSDALE RD,...,C,Papago/North Tempe,N,11,85288.0,4.013320e+09,NaN,NaN,697015.0,890426.0

In [5]:
list(dfCrime.columns)

['OBJECTID',
 'PrimaryKey',
 'OccurrenceDatetime',
 'OccurrenceYear',
 'OccurrenceMonth',
 'OccurrenceHour',
 'OccurrenceWeek',
 'OccurrenceDatePart',
 'OccurrenceWeekday',
 'ObfuscatedAddress',
 'XCoordinate',
 'YCoordinate',
 'Disclaimer',
 'PlaceName',
 'OffenseCustom',
 'LocationTranslation',
 'Latitude',
 'Longitude',
 'RucrComp',
 'CharacterArea',
 'ReportDistrict',
 'ReportBeat',
 'PostalCode',
 'CensusTractID',
 'ParkName',
 'NeighborhoodName',
 'x',
 'y']

In [6]:
list(dfCrime['OffenseCustom'].unique())

['NARCOTIC DRUG-POSSESSION                                                        ',
 'ASSAULT                                                                         ',
 'DEATH                                                                           ',
 'BURGLARY FROM VEHICLE                                                           ',
 'ROBBERY-ARMED                                                                   ',
 'DRUG PARAPHERNALIA                                                              ',
 'CRIMINAL DAMAGE                                                                 ',
 'CHILD ABUSE                                                                     ',
 'CHILD CRIMES INFORMATION                                                        ',
 'SHOPLIFTING                                                                     ',
 'DANGEROUS DRUG-POSSESSION                                                       ',
 'ACCIDENT-HIT AND RUN                                                            ',
 'THEFT FROM BUILDING                                                             ',
 'AGGRAVATED ASSAULT DV                                                           ',
 'DISORDERLY CONDUCT                                                              ',
 'MOTOR VEHICLE THEFT                                                             ',
 'TRESPASSING                                                                     ',
 'ACCIDENT-NO INJURY                                                              ',
 'ACCIDENT-INJURY                                                                 ',
 'VEHICLE IMPOUND                                                                 ',
 'MARIJUANA-POSSESSION                                                            ',
 'THEFT OTHER                                                                     ',
 'DUI-LIQUOR                                                                      ',
 'COUNTERFEIT MONEY                                                               ',
 'CRIMINAL DAMAGE VEHICLE                                                         ',
 'IDENTITY THEFT                                                                  ',
 'FORGERY                                                                         ',
 'AGGRAVATED ASSAULT                                                              ',
 'THEFT OF LICENSE PLATE                                                          ',
 'BURGLARY FORCE                                                                  ',
 'INTERFERE JUDICIAL PROCEEDINGS                                                  ',
 'ASSIST OTHER AGENCY                                                             ',
 'HARASSMENT                                                                      ',
 'SUSP/CANC/REV DRIVERS LICENSE                                                   ',
 'BURGLARY NO FORCE                                                               ',
 'FRAUD-USE OF CREDIT CARD                                                        ',
 'SEX OFFENDER-FAIL REG/CHNG ADD                                                  ',
 'OTHER TRAFFIC OFFENSE                                                           ',
 'VIOLATE ORDER OF PROTECTION                                                     ',
 'THEFT OF A CREDIT CARD                                                          ',
 'ROBBERY-STRONG ARM                                                              ',
 'THREAT/INTIMIDATE PERSON                                                        ',
 'COMMERCIAL VEHICLE INSPECTION                                                   ',
 'SEXUAL ASSAULT                                                                  ',
 'THEFT OF SERVICES                                                               ',
 'AGGRAVATED ASSAULT-POLICE OFC                                                   ',
 'RUNAWAY JUVENILE                                                                ',
 'PRESCRIPTION DRUG-POSS/MANUFA                                                   ',
 'THEFT OF MOTOR VEHICLE PARTS                                                    ',
 'FALSE REPORTING                                                                 ',
 'FRAUD                                                                           ',
 'THEFT OF BICYCLE                                                                ',
 'FOUND FIREARM                                                                   ',
 'MOTOR VEH THEFT-RECOVERED FOJ                                                   ',
 'LIQUOR LAW VIOLATION                                                            ',
 'SEXUAL ABUSE                                                                    ',
 'THREAT/INTIMIDATE PROPERTY                                                      ',
 'OTHER CRIMINAL OFFENSE                                                          ',
 'CRIMINAL LITTERING/POLLUTING                                                    ',
 'THEFT BY EMBEZZLEMENT                                                           ',
 'BURGLARY FROM YARD                                                              ',
 'DUI-DRUGS                                                                       ',
 'SUICIDE                                                                         ',
 'INJURY                                                                          ',
 'STOLEN PROPERTY-POSSESSION                                                      ',
 'FIRE INFORMATION                                                                ',
 'CUSTODIAL INTERFERENCE                                                          ',
 'CITY CODE VIOLATION                                                             ',
 'DANGEROUS DRUG-SELL/MANUFACTUR                                                  ',
 'STOLEN PROPERTY-TRAFFICKING                                                     ',
 'MOTOR VEHICLE THEFT TRAILER                                                     ',
 'FRAUD SCHEMES                                                                   ',
 'NARCOTIC DRUG-SELL/MANUFACTURE                                                  ',
 'DUI-AGGRAVATED                                                                  ',
 'STALKING                                                                        ',
 'MARIJUANA-SELL/MANUFACTURE                                                      ',
 'DELAY/OBSTRUCT POLICE OFFICER                                                   ',
 'WEAPON OFFENSE                                                                  ',
 'ACCESS INTERFERENCE                                                             ',
 'THEFT FROM MOTOR VEHICLE                                                        ',
 'UNLAWFUL USE OF TRANSPORTATION                                                  ',
 'THEFT BY PICK POCKETING                                                         ',
 'THREAT/INTIMIDATE PERSON W/GUN                                                  ',
 'THEFT BY PURSE SNATCHING                                                        ',
 'FORGERY-PRESCRIPTION                                                            ',
 'VOYEURISM/PEEPING TOM                                                           ',
 'HOMICIDE                                                                        ',
 'STOLEN PROPERTY-RECOVERED FOJ                                                   ',
 'VIOLATE HARASSMENT INJUNCTION                                                   ',
 'URINATING/DEFACATING IN PUBLIC                                                  ',
 'MISSING PERSON-RECOVERED FOJ                                                    ',
 'MISSING ADULT                                                                   ',
 'INDECENT EXPOSURE                                                               ',
 'UNLAWFUL IMPRISONMENT                                                           ',
 'INTERFERE EDUCATIONAL INST                                                      ',
 'MANSLAUGHTER                                                                    ',
 'PUBLIC SEXUAL INDECENCY                                                         ',
 'CHILD NEGLECT                                                                   ',
 'OTHER SEXUAL OFFENSE                                                            ',
 'MISSING JUVENILE                                                                ',
 'FUGITIVE FROM JUSTICE                                                           ',
 'THEFT BY EXTORTION                                                              ',
 'UNLAWFUL FLIGHT                                                                 ',
 'SURREPTITIOUS VIEWING                                                           ',
 'COCAINE-POSSESSION                                                              ',
 'OTHER DRUG OFFENSE                                                              ',
 'TOWING VIOLATION/SIGNAGE                                                        ',
 'SEXUAL CONDUCT WITH MINOR                                                       ',
 'PROSTITUTION                                                                    ',
 'RESISTING ARREST                                                                ',
 'FAILURE TO RETURN RENTAL CAR                                                    ',
 'FRAUD-IMPERSONATION                                                             ',
 'AGGRAVATED CRIMINAL DAMAGE                                                      ',
 'ANIMAL CRUELTY                                                                  ',
 'ARSON-STRUCTURE                                                                 ',
 'ARSON-OTHER PROPERTY                                                            ',
 'ENDANGERMENT                                                                    ',
 'SEXUAL EXPLOITATION OF A MINOR                                                  ',
 'KIDNAPPING                                                                      ',
 'DRIVE BY SHOOTING                                                               ',
 'RECKLESS BURNING                                                                ',
 'CONTRIBUTING DELINQUENCY MINOR                                                  ',
 'ASSIST/PROMOTE PROSTITUTION                                                     ',
 'LURING MINOR SEX EXPLOITATION                                                   ',
 'COCAINE-SELL/MANUFACTURE                                                        ',
 'OFCR INVOLVED FATAL SHOOTING                                                    ',
 'ACCIDENT-FATALITY                                                               ',
 'PORNOGRAPHY-OBSCENE MATERIAL                                                    ',
 'THEFT FROM COIN OPERT MACHINE                                                   ',
 'COMPUTER TAMPERING                                                              ',
 'ARSON-MOBILE                                                                    ',
 'FAILURE TO RETURN RENTAL PROP                                                   ',
 'MOLESTATION OF A CHILD                                                          ',
 'HOMICIDE-NEGLIGENT                                                              ',
 'CHILD PROSTITUTION                                                              ',
 'CONSPIRACY OF A CRIME                                                           ',
 'REMOVE/ALTER/DAMAGE VIN                                                         ',
 'TERRORISM                                                                       ',
 'POSSESS FORGERY DEVICE                                                          ',
 'POSSESS BURGLARY TOOLS                                                          ',
 'BESTIALITY                                                                      ',
 'ESCAPE                                                                          ',
 'OFCR INVOLVED SHOOTING                                                          ',
 'TRAFFIC MANSLAUGHTER                                                            ',
 'HUMAN TRAFFICKING SEX ACTS                                                      ',
 'SOLICITATION OF A CRIME                                                         ',
 'FOUND FIREARM / AMMUNITION                                                      ',
 'SEXUAL ABUSE/FONDLING                                                           ',
 nan]

In [7]:
violentCrimes = ['AGGRAVATED ASSAULT                                                              ',
                 'AGGRAVATED ASSAULT DV                                                           ',
                 'AGGRAVATED ASSAULT-POLICE OFC                                                   ',
                 'HOMICIDE                                                                        ',
                 'MANSLAUGHTER                                                                    ',
                 'MOLESTATION OF A CHILD                                                          ',
                 'ROBBERY-ARMED                                                                   ',
                 'ROBBERY-STRONG ARM                                                              ',
                 'SEXUAL ABUSE                                                                    ',
                 'SEXUAL ABUSE/FONDLING                                                           ',
                 'SEXUAL ASSAULT                                                                  ']
propertyCrimes = ['BURGLARY NO FORCE                                                               ',
                  'BURGLARY FROM VEHICLE                                                           ',
                  'BURGLARY FROM YARD                                                              ',
                  'THEFT OF BICYCLE                                                                ',
                  'THEFT OTHER                                                                     ',
                  'MOTOR VEHICLE THEFT                                                             ',
                  'BURGLARY FORCE                                                                  ',
                  'THEFT FROM MOTOR VEHICLE                                                        ',
                  'THEFT FROM BUILDING                                                             ',
                  'THEFT OF A CREDIT CARD                                                          ',
                  'MOTOR VEHICLE THEFT TRAILER                                                     ',
                  'THEFT BY PICK POCKETING                                                         ',
                  'THEFT BY EXTORTION                                                              ',]
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['OffenseCustom'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(20942, 28)

,OBJECTID,PrimaryKey,OccurrenceDatetime,OccurrenceYear,OccurrenceMonth,OccurrenceHour,OccurrenceWeek,OccurrenceDatePart,OccurrenceWeekday,ObfuscatedAddress,...,RucrComp,CharacterArea,ReportDistrict,ReportBeat,PostalCode,CensusTractID,ParkName,NeighborhoodName,x,y
29656,109921689,TE201818686,2/12/2018 10:00:00 PM,2018.0,2.0,22.0,7.0,12.0,Monday,2XXX E FREMONT DR,...,C,Kiwanis/The Lakes,S,22,85282.0,4.013319e+09,NaN,Cole Park,705054.0,867024.0
46405,109938438,TE201729363,3/12/2017 12:08:00 AM,2017.0,3.0,0.0,11.0,12.0,Sunday,1XXX N SCOTTSDALE RD,...,C,Papago/North Tempe,N,11,85288.0,4.013320e+09,NaN,NaN,697015.0,890426.0
104716,109996749,TE201729332,3/11/2017 11:00:00 PM,2017.0,3.0,23.0,10.0,11.0,Saturday,5XXX S MILL AVE,...,C,Kiwanis/The Lakes,S,21,85282.0,4.013320e+09,NaN,NaN,693068.0,865585.0
105019,109997052,TE201891239,8/5/2018 9:46:00 AM,2018.0,8.0,9.0,32.0,5.0,Sunday,2XXX E RIO SALADO PKWY,...,C,Apache,N,15,85288.0,4.013318e+09,NaN,NaN,706092.0,883747.0
105041,109997074,TE201892001,8/7/2018 9:20:00 AM,2018.0,8.0,9.0,32.0,7.0,Tuesday,1XXX E DON CARLOS AVE,...,C,Apache,N,15,85281.0,4.013319e+09,NaN,Alegre Community,703266.0,879432.0

In [8]:
dfCrime = dfCrime[['OffenseCustom', 'Latitude', 'Longitude']]

# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['OffenseCustom', 'geometry']]
dfCrime.head()

,OffenseCustom,geometry
29656,BURGLARY FROM VEHICLE ...,POINT (-111.900109 33.383395)
46405,ROBBERY-ARMED ...,POINT (-111.926453 33.447714)
104716,BURGLARY FROM VEHICLE ...,POINT (-111.939376 33.379439)
105019,THEFT FROM BUILDING ...,POINT (-111.896698 33.429356)
105041,AGGRAVATED ASSAULT DV ...,POINT (-111.905963 33.417498)

In [9]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_04_bg_500k/cb_2018_04_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(4178, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,04,013,071600,2,1500000US040130716002,040130716002,2,BG,792496,13210,"POLYGON ((-112.3 33.594, -112.3 33.594, -112.3..."
1,04,013,071910,3,1500000US040130719103,040130719103,3,BG,355984,0,"POLYGON ((-112.23 33.593, -112.23 33.593, -112..."
2,04,013,082209,2,1500000US040130822092,040130822092,2,BG,682319,0,"POLYGON ((-112.3 33.434, -112.3 33.435, -112.2..."
3,04,019,004025,4,1500000US040190040254,040190040254,4,BG,3950996,0,"POLYGON ((-110.82 32.281, -110.82 32.28, -110...."
4,04,013,319903,3,1500000US040133199033,040133199033,3,BG,683166,0,"POLYGON ((-111.93 33.372, -111.93 33.371, -111..."

In [16]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

,OffenseCustom,geometry
29656,BURGLARY FROM VEHICLE ...,POINT (-111.9 33.383)
46405,ROBBERY-ARMED ...,POINT (-111.93 33.448)
104716,BURGLARY FROM VEHICLE ...,POINT (-111.94 33.379)
105019,THEFT FROM BUILDING ...,POINT (-111.9 33.429)
105041,AGGRAVATED ASSAULT DV ...,POINT (-111.91 33.417)

In [19]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(20942, 13)

,OffenseCustom,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
29656,BURGLARY FROM VEHICLE ...,POINT (-111.9 33.383),611.0,04,013,319402,2,1500000US040133194022,040133194022,2,BG,1283178.0,0.0
46405,ROBBERY-ARMED ...,POINT (-111.93 33.448),799.0,04,013,320100,2,1500000US040133201002,040133201002,2,BG,579544.0,0.0
104716,BURGLARY FROM VEHICLE ...,POINT (-111.94 33.379),2266.0,04,013,319800,2,1500000US040133198002,040133198002,2,BG,312265.0,0.0
105019,THEFT FROM BUILDING ...,POINT (-111.9 33.429),1054.0,04,013,318400,2,1500000US040133184002,040133184002,2,BG,6105562.0,156123.0
105041,AGGRAVATED ASSAULT DV ...,POINT (-111.91 33.417),65.0,04,013,319201,2,1500000US040133192012,040133192012,2,BG,382504.0,0.0

In [21]:
crime = result['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US040133187002    510.333333
1500000US040133184002    320.000000
1500000US040133197041    291.666667
1500000US040133197031    282.666667
1500000US040133199101    204.000000
                            ...
1500000US040134222051      0.666667
1500000US040133200023      0.666667
1500000US040134222123      0.333333
1500000US040131162052      0.333333
1500000US040133200021      0.333333
Name: count, Length: 116, dtype: float64

In [23]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Tempe_All_Crime_BG.csv')

In [25]:
result2 = result[result['OffenseCustom'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US040133187002    100.000000
1500000US040133184002     39.666667
1500000US040133197041     36.333333
1500000US040133197031     27.333333
1500000US040133192012     26.666667
                            ...
1500000US040138101004      0.666667
1500000US040134222051      0.666667
1500000US040133199062      0.666667
1500000US040133200023      0.333333
1500000US040133199042      0.333333
Name: count, Length: 112, dtype: float64

In [27]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Tempe_Violent_Crime_BG.csv')

In [29]:
result3 = result[result['OffenseCustom'].isin(propertyCrimes)]
crime = result3['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US040133187002    410.333333
1500000US040133184002    280.333333
1500000US040133197041    255.333333
1500000US040133197031    255.333333
1500000US040133199101    193.000000
                            ...
1500000US040133200024      0.666667
1500000US040134222123      0.333333
1500000US040131162052      0.333333
1500000US040133200023      0.333333
1500000US040133200021      0.333333
Name: count, Length: 115, dtype: float64

In [31]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Tempe_Property_Crime_BG.csv')

In [33]:
result4 = result[result['OffenseCustom'].isin(['MOTOR VEHICLE THEFT                                                             '])]
crime = result4['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US040133184002    30.666667
1500000US040133197031    27.333333
1500000US040133197041    26.000000
1500000US040133199101    17.000000
1500000US040133187002    16.000000
                           ...
1500000US040133196001     0.333333
1500000US040133199054     0.333333
1500000US040133200023     0.333333
1500000US040138101003     0.333333
1500000US040138101001     0.333333
Name: count, Length: 112, dtype: float64

In [35]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Tempe_MV_Crime_BG.csv')